version: '3'

services:
  movie:
    build:
      context: .
      dockerfile: Dockerfile
    image: movie
    container_name: movie
    hostname: movie
    restart: always
    command: python /movie/manage.py runserver 0.0.0.0:8820
    volumes:
      - .:/movie
    ports:
      - "8820:8820"
    depends_on:
      - mysql  

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost 
      - MYSQL_PORT=3306 
      - MYSQL_DATABASE=movie
      - MYSQL_USER=movie_dev
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
